language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

jobs:
  allow_failures:
    - php: nightly

install:
  - composer install --dev --ignore-platform-reqs

script:
  - composer ci
